### ISSUE TITLE
[DOCUMENT] Add directories for each teams

### ISSUE THREAD

**Issue by devFallingstar** [Solidity-Study-GachonSoftware/Documentation#1]
Have to add directories for each teams

Each teams' name would be

- KYA
- Something
- LoV3Ch@!n

**Comment by devFallingstar** [comment]
My name is KYA

**Comment by hamellun** [comment]
My name is something

**Comment by snaag** [comment]
My name is LoV3Ch@!n

**Comment by devFallingstar** [comment]
#2 #3 #4 Done
